# Generated by Django 4.2.4 on 2023-08-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Aspiration',
            new_name='aspiration',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='interests',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='strengths',
            new_name='strength',
        ),
    ]
